#NN Settings
skip_training = false
log = 10
batchSize = 1
hiddenLayers = 13
lookAheadCandles = 5
iterations = 200
error = 0.001
learnRate = 0.05
momentum = 0.1
dropout = 0.3
max_possible_price = 0.00024

#Strat Settings
long_at_percent = 0.05
short_at_percent = 0.05

